Added option for run result
inluxc/playwright-xray pull request #81
Opened 2024-11-18 20:10 UTC by NiklasBack

This PR includes a configuration option to write a JSON file that summarizes the test run. The ANSI stripper has also been changed to include the functionality of strip-ansi. Also the reporter will only report the execution result of the first browser being run, e.g. if the same test cases ar run with both chrome and firefox in order to addressed in issue raised in #77.

2024-11-18 23:01 UTC, inluxc requested changes

2024-11-18 23:01 UTC, inluxc commented on src/xray.service.ts
> +        console.log(`${bold(green(`😀 Successfully sending test results to Jira`))}`);
There is some brackets over here :rofl:

2024-11-19 09:21 UTC, Niklas-Back commented on src/xray.service.ts
> +        console.log(`${bold(green(`😀 Successfully sending test results to Jira`))}`);
Fixed 😄

2024-11-20 15:52 UTC, inluxc approved these changes
All checked

2024-11-20 15:52 UTC, merged